spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exampledb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      generate_statistics: true
      ddl-auto: validate
